version: "3.7"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 4444 --reload
    # build: ./backend/app
    volumes:
      - ./backend/app:/api/app
    container_name: api
    ports:
      - "4444:4444"
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    command: npm run start
    volumes:
      # - ./frontend:/web
      - ./frontend/src:/app/src
    container_name: web
    ports:
      - "8080:8080"